[.text-center]
Министерство науки и высшего образования Российской Федерации Федеральное государственное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (Национальный исследовательский университет)

[.text-center]
Высшая школа электроники и компьютерных наук Кафедра «Информационно-измерительная техника»

[.text-center]
дисциплина: 1.Ф.П1.06 (Программное обеспечение измерительных процессов)

[.text-center]
Отчет №1 +
на тему "Запуск программного обеспечения на микроконтроллере" 

[.text-right]
Работу принял, доцент +
___/ С.В. Колодий / +
___2023 г.

[.text-right]
Автор работы +
студент группы КЭ-413 +
___/ А.И. Кривоносов / +
___2023 г.

[.text-center]
Челябинск 2023

== Оглавление

<<1 Запуск программного обеспечения на микроконтроллере>>

<<2 Ответы на вопросы по теме>>

== 1 Запуск программного обеспечения на микроконтроллере

Запуск программного обеспечения происходит поэтапно:

* после подачи питания происходит инициализация указателя стека. Указатель стека указывает на последний байт последнего элемента, добавленного в стек и хранится в регистрах процессора. Регистр адреса команды указывает на 0 адрес, и микроконтроллер начинает работу с адреса 0. Последовательность последующих команд определяется счётчиком программ. Счётчик программ - это регистр микропроцессора, который имеет адрес следующей команды, которая должна быть выполнена из памяти;
* выполнение функции инициализации глобальных нулевых переменных (zero-initialized data, например, int i);
* инициализация заданных переменных (initialized data, например, int i = 1), значения для каждой переменной будут скопированы из ПЗУ в ОЗУ;
* вызов функции main() и далее остального кода.

== 2 Ответы на вопросы по теме

1) Дайте определение понятию "Интегрированная среда разработки".
 
* Ответ: это совокупность программных средств для разработки ПО.

2) Что такое компилятор и чем он отличается от транслятора?

* Ответ: компилятор это программа, преобразующая код на языке программирования в машинный код. Он отличается от транслятора тем, что его конечная программа обязательно написана в виде машинного кода или языка ассемблера.

3) Что такое компоновщик и какие функции он выполняет?

* Ответ: компоновщик это программа, которая создает исполняемый файл для целевой платформы из объектов на входе (библиотеки, объектные файлы).

4) Почему важен процесс проектирования ПО? Какие задачи входят в этот процесс?

* Ответ: проектирование ПО важно, потому что оно позволяет:
 ** оценить затрачиваемые на это ресурсы до начала создания;
 ** избежать разногласий между заказчиком и исполнителем;
 ** обеспечить повторяемость;
 ** повысить качество ПО, вследствие того, что выявление ошибок в коде будет осуществляться на ранних этапах разработки.

* В процесс проектирования входят:
 ** выбор описания, архитектуры программы, метода и стратегии решения, выбор внутренних данных;
 ** составление ТЗ;
 ** создание "макетов" интерфейсов, принципиальных схем устройств, диаграмм структуры базы данных, определение схемы взаимодействия компонентов;
 ** контроль экспертами;
 ** документирование ПО;
 ** утверждение ТЗ. 

6) Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?

* Ответ: отладка нужна для поиска и устранения ошибок в приложениях. Точки остановки применяются для контроля выполнения программы на определенных шагах алгоритма.