:imagesdir: Report3Img
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
:toc: macro

[.text-center]
Министерство науки и высшего образования Российской Федерации Федеральное государственное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (Национальный исследовательский университет) +
Высшая школа электроники и компьютерных наук +
Кафедра «Информационно-измерительная техника» +
 +
дисциплина: 1.Ф.П1.06 (Программное обеспечение измерительных процессов) +
 +
Отчет №3 +
на тему "Указатели и ссылки" 

[.text-right]
Работу принял, доцент +
/ С.В. Колодий / +
2023 г. +
 +
Автор работы +
студент группы КЭ-413 +
/ А.И. Кривоносов / +
2023 г.

[.text-center]
Челябинск 2023

toc::[]

== Задание

. Написать какая информация про указатели и ссылки была новой для студента.

Каждой переменной, содержащей данные, соответствует адрес памяти. К переменной можно обратиться непосредственно обращаясь к самой переменной либо можно обратиться косвенно, то есть через указатель или ссылку.

=== Указатели

Указатель это переменная, которая хранит адрес другой переменной. Размер указателя для микроконтроллера STM32 4 байта (32 бита). Пример использования указателя, для инициализации указателя используется символ "*":

[source, cpp]

----
int main() {
  int  c = 463 ;   # <1>
  int* ptr = &c ;  # <2>
  return 0;
}
----

Указатели можно складывать, вычитать, сравнивать, но указатели должны быть одного типа. Также у указателя можно взять адрес, который будет являться адресом переменной, связанной с этим указателем.

Указатели могут указывать на переменные и на константы. +
Чтобы определить указатель на константу, он тоже должен объявляться через "const", как и константа. Изменять значение по адресу, который хранится в указателе на константу, не рекомендуется, так как может возникнуть ситуация Undefined Behaviour, но возможно присвоить указателю адрес любой другой константы.

Ещё есть константные указатели, которые определяются через "*const". Они не могут изменять адрес, который в них хранится, но могут изменять значение по этому адресу.

А также существуют константные указатели на константу, которые не позволяют менять ни хранимый в них адрес, ни значение по этому адресу. Они определяются как, например:
[source, cpp]

----
int a {10};
const int *const pa {&a};
----

=== Ссылки

Ссылка это псевдоним переменной.

Пример использования ссылки, для инициализации ссылки используется символ "&":

[source, cpp]

----
int main(){
  int a = 0;
  int &ref = a ;                
  ref = 10;                     
  cout << &ref << ": " << ref ; 
  return 0 ;
}
----

У ссылок есть ряд особенностей:

* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведен адрес переменной, на которую она ссылается;

* ссылку нельзя изменять, складывать, вычитать, как и константный указатель;

* ссылки нельзя сравнивать;

* ссылка не может быть не проинициализирована.

== Вывод

Была получена новая информация по указателям, операциям с указателями, константным указателям и указателям на константу, а также по ссылкам.