= Запуск программного обеспечения на микроконтроллере

После подачи питания происходит инициализация указателя стека. Указатель стека указывает на последний байт последнего элемента, добавленного в стек и хранится в регистрах процессора. Регистр адреса команды указывает на 0 адрес, а микроконтроллер начинает работу с адреса 0.

Далее выполняется функция инициализации глобальных нулевых переменных (zero-initialized data, например, int i). Затем инициализируются заданные переменные (initialized data, например, int i = 1), значения для каждой переменной будут скопированы из ПЗУ в ОЗУ.

После инициализации указателя стека, нулевых и ненулевых переменных происходит вызов функции main() и далее остального кода.

== Ответы на вопросы по теме

1) Дайте определение понятию "Интегрированная среда разработки".
 
* Ответ: это совокупность программных средств для разработки ПО.

2) Что такое компилятор и чем он отличается от транслятора?

* Ответ: компилятор это программа, преобразующая код на языке программирования в машинный код. Он отличается от транслятора тем, что его конечная программа обязательно написана в виде машинного кода или языка ассемблера.

3) Что такое компоновщик и какие функции он выполняет?

* Ответ: компоновщик это программа, которая создает исполняемый файл для микроконтроллера из объектов на входе (библиотеки, объектные файлы).

4) Почему важен процесс проектирования ПО? Какие задачи входят в этот процесс?

* Ответ: проектирование ПО важно, потому что оно позволяет оценить затрачиваемые на это ресурсы до начала создания и позволяет избежать разногласий между заказчиком и исполнителем. В процесс проектирования входят:
  ** выбор описания и архитектуры программы;
  ** составление ТЗ;
  ** определение схемы взаимодействия компонентов;
  ** утверждение ТЗ.

6) Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?

* Ответ: отладка нужна для поиска и устранения ошибок в приложениях. Точки остановки применяются для контроля выполнения программы на определенных шагах алгоритма.