:imagesdir: Lab8Img
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
:toc: macro
:stem:

include::Titul.adoc[lines="1..8"]
Разработка устройства индикации напряжения +
Пояснительная записка к курсовому проекту
include::Titul.adoc[lines="11..23"]

toc::[]

== Анализ требований

По требованиям для разработки должна использоваться отладочная плата XNUCLEO-F411RE.

Софт должен измерять напряжение с переменного резистора, установленного на плате расширения.

Для измерения напряжения должен использоваться встроенный АЦП.

Период измерения должен быть 50 мс.

Для получения кода измерения должен использоваться механизм DMA.

Для изменения напряжения должна использоваться плата Accessories Shield.

Точность измерения напряжения должна быть не менее 0,01 вольта.

К измеренному напряжению должен быть применен цифровой фильтр вида: +
stem:[tau = int  ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))] +
{nbsp} +
stem:["FilteredValue" = "OldValue" + ("Value" - "OldValue") * tau], +
{nbsp} +
где dt -  100 мс; +
Value – текущее нефильтрованное измеренное значение напряжения; +
oldValue -  предыдущее фильтрованное значение.

Индикация значения измеренного напряжения должна осуществляться через включение/выключение светодиодов. При максимальном напряжении софт должен зажигать 4 светодиода, при минимальном все светодиоды должны погаснуть.

Промежуточные значения напряжения должны индицироваться следующим образом:

* при 0-25% от максимального напряжения зажигается только 1 светодиод;
* при 25-50% от максимального напряжения зажигается только 2 светодиода;
* при 50-75% от максимального напряжения зажигается только 3 светодиода;
* при 75-100% от максимального напряжения зажигается все 4 светодиода.

Передача значений по беспроводному интерфейсу должна осуществляться через модуль BlueTooth Bee HC-06
 или I/O Expansion Shield.

Общение с платой расширения должно осуществляться через USART2.

Формат вывода: +
   "Напряжение: " X.XXX [Units]

Архитектура должна быть представлена в виде UML диаграмм в пакете Star UML. Приложение должно быть написано на языке С++ с использование компилятора ARM 8.40.2. При разработке должна использоваться Операционная Система Реального Времени FreeRTOS и RtosWrapper.