:imagesdir: Lab8Img
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
:toc: macro
:stem:

include::Titul.adoc[lines="1..8"]
Разработка устройства индикации напряжения +
Пояснительная записка к курсовому проекту
include::Titul.adoc[lines="11..23"]

toc::[]

== Анализ требований

[cols="1,1"]
|===
|Параметр, характеристика |Требование

|Отладочная плата
|XNUCLEO-F411RE

|Способ измерения напряжения
|Встроенный АЦП

|Период измерения
|50 мс

|Получение кода измерения
|Механизм DMA

|Изменение напряжения
|Плата Accessories Shield, переменный резистор

|Точность измерения напряжения
|Не менее 0,01 В

|Общение с платой расширения
|USART2

|Передача значений по беспроводному интерфейсу
|BlueTooth Bee HC-06 или I/O Expansion Shield

|Язык приложения, компилятор
|C++, ARM 8.40.2
|===

К измеренному напряжению должен быть применен цифровой фильтр вида: +
stem:[tau = int  ((1-e^(-dt/(R*C)), RC > 0 sec), (1, RC<= 0 sec))] +
{nbsp} +
stem:["FilteredValue" = "OldValue" + ("Value" - "OldValue") * tau], +
{nbsp} +
где dt -  100 мс; +
Value – текущее нефильтрованное измеренное значение напряжения; +
oldValue -  предыдущее фильтрованное значение.

Индикация значения измеренного напряжения должна осуществляться через включение/выключение светодиодов. При максимальном напряжении софт должен зажигать 4 светодиода, при минимальном все светодиоды должны погаснуть.

Промежуточные значения напряжения должны индицироваться следующим образом:

* при 0-25% от максимального напряжения зажигается только 1 светодиод;
* при 25-50% от максимального напряжения зажигается только 2 светодиода;
* при 50-75% от максимального напряжения зажигается только 3 светодиода;
* при 75-100% от максимального напряжения зажигается все 4 светодиода.

Формат вывода: +
   "Напряжение: " X.XXX [Units]

Архитектура должна быть представлена в виде UML диаграмм в пакете Star UML. При разработке должна использоваться Операционная Система Реального Времени FreeRTOS и RtosWrapper.