:imagesdir: Lab8Img
:figure-caption: Рисунок
:table-caption: Таблица
:toc-title: Оглавление
:toc: macro

include::Titul.adoc[lines="1..8"]
Отчет по лабораторной работе №8
include::Titul.adoc[lines="11..23"]

toc::[]

== Задание

. Написать что было изучено про прерывания на лекции;

. Написать программу, которая будет переключать все светодиоды с периодом 0,5 секунды. По нажатию кнопки увеличивать период моргания на 0,1 секунды. При достижении периода 1 секунда сбрасывать до 0,5 секунды. Для задания периода использовать таймер TIM2 (для данного варианта), а прерывания для кнопки сделать через TIM5.

=== Прерывания

Прерывание - это сигнал, сообщающий микропроцессору о наступлении какого-либо события от переферии. При этом выполнение текущей последовательности команд останавливается, и управление передаётся обработчику прерывания, который реагирует на событие и обслуживает его, после чего возвращает управление в прерванный код.

В зависимости от источника прерывания бывают:

* асинхронные;
* синхронные;
* программные.

А также различают маскируемые (могут запрещаться и разрешаться) и немаскируемые (не могут запрещаться) прерывания. 

Вектор прерывания закрепленный за устройством номер, который идентифицирует соответствующий обработчик прерываний. Векторы прерываний объединяются в таблицу векторов прерываний (список векторов прерываний).

Управление и обработка прерываниями производится контроллером приоритетных векторных прерываний (NVIC), который является частью ядра Cortex-M.

=== Программа

В startupF411RE.cpp были добавлены строчки:
[source, cpp, linenums]
----
#include "timer5config.h" // for tTimer5
----
и
[source, cpp, linenums]
----
tTimer5::handler,	        //TIM5 global interrupt
----

Листинг allflickmode.h
[source, cpp, linenums]
----
#ifndef ALLFLICKMODE
#define ALLFLICKMODE

#include "imode.h" // for IMode
#include <array>

template<auto&...pins>
class AllFlickMode : public IMode
{
public:
  void Update() override
  {
    for(std::size_t i = 0; i < leds.size(); i++)
    {
      leds[i]->Toggle();
    }
  }
  void SetToDefault() override
  {
    for(auto it: leds)
    {
      it->Off();
    }
  }
private:
  std::array<IPin*, sizeof ...(pins)> leds = {&pins...};
};

#endif
----

Листинг timer5config.h
[source, cpp, linenums]
----
#ifndef TIMER5CONFIG
#define TIMER5CONFIG

#include "timer5.h" // for Timer5
#include "pin.h" // for pin.h
#include "button.h" // for button
#include "gpiocregisters.hpp" // for GPIOC
#include "gpioaregisters.hpp" // for GPIOA

extern Pin<GPIOA,5> pin1 ;
extern Pin<GPIOC,9> pin2 ;
extern Pin<GPIOC,8> pin3 ;
extern Pin<GPIOC,5> pin4 ;

extern Button<GPIOC, 13> button;
extern std::uint32_t period; 

using tTimer5 = Timer5<button, period>;

#endif
----

Листинг timer5.h
[source, cpp, linenums]
----
#ifndef TIMER5
#define TIMER5

#include "tim5registers.hpp" //for TIM5

using tMsec = std::uint32_t;
template <auto& button, auto& period>
class Timer5
{
public:
  static void handler()
  {
    if(TIM5::SR::UIF::InterruptPending::IsSet() and 
       TIM5::DIER::UIE::Value1::IsSet())
    {
      if(button.IsPressed())
      {
        period = (period <= tMsec(1000)) ? (period + tMsec(100U)) : tMsec(500U);
      }
      TIM5::SR::UIF::NoInterruptPending::Set();
    }
  }
};

#endif
----

Листинг main.cpp
[source, cpp, linenums]
----
#include "rccregisters.hpp" // for RCC
#include "gpioaregisters.hpp" // for GPIOA
#include "pin.h" // for LED toggle
#include "button.h" // for reсord button push 
#include "gpiocregisters.hpp" // for GPIOC
#include "allflickmode.h" // for AllFlickMode
#include "stkregisters.hpp" // for STK
#include "scbregisters.hpp" // for ICSR
#include "tim2registers.hpp" // for TIM2
#include "tim5registers.hpp" // for TIM5
#include "nvicregisters.hpp" // for NVIC

const std::uint32_t SystemCoreClock = 16'000'000U;
std::uint32_t period = 500U;

extern "C"
{
  int __low_level_init(void)
  {
    RCC::APB1ENR::TIM2EN::Enable::Set();
    NVIC::ISER0::Write(1 << 50U); // разрешили глобальное прерывание для TIM5
    
    const auto TimerDevider = SystemCoreClock / 1'000;
    
    TIM5::PSC::Write(TimerDevider);
    TIM5::CR1::URS::Value1::Set();
    TIM5::ARR::Write(period);
    TIM5::SR::UIF::Set(0);
    TIM5::CNT::Write(0);
    TIM5::DIER::UIE::Value1::Set(); // разрешили прерывание по переполнению
    TIM5::CR1::CEN::Enable::Set();
    return 1;
  }
}

using tMsec = std::uint32_t;
void delay(tMsec period)
{
  const auto TimerDevider = SystemCoreClock / 1'000U;
  TIM2::PSC::Write(TimerDevider);
  TIM2::CR1::URS::OverflowEvent::Set();
  TIM2::ARR::Write(period);
  TIM2::SR::UIF::Set(0);
  TIM2::CNT::Write(0);
  TIM2::CR1::CEN::Enable::Set();
  while (TIM2::SR::UIF::Get() == 0U)
  {
  }
  TIM2::CR1::CEN::Disable::Set();
  TIM2::SR::UIF::Set(0);
}

Pin<GPIOA,5> pin1 ;
Pin<GPIOC,9> pin2 ;
Pin<GPIOC,8> pin3 ;
Pin<GPIOC,5> pin4 ;
AllFlickMode<pin1, pin2, pin3, pin4> allflickMode;
Button<GPIOC, 13> button;
int main()
{
  GPIOC::MODER::MODER13::Input::Set() ;
  //Подать тактирование на порт А
  RCC::AHB1ENR::GPIOAEN::Enable::Set() ;
  //Подать тактирование на порт С
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  GPIOA::MODER::MODER5::Output::Set() ; // установить порт А.5 на выход
  //Светодиоды на портах C.5,C.8, C.9 на выход
  GPIOC::MODER::MODER5::Output::Set() ;
  GPIOC::MODER::MODER8::Output::Set() ;
  GPIOC::MODER::MODER9::Output::Set() ;
  
  tMsec period = 500U;
  for(;;)
  {
    allflickMode.Update();
    delay(period);
  }
  
  return 1;
}
----

На видео представлена работа программы.

.Видео - Демонстрация работы программы
video::Video.mp4[opts="muted"]

== Вывод по работе
В ходе данной работы было проведено ознакомление с прерываниями. Была написана программа, которая переключает светодиоды по заданному алгоритму.